# Generated by Django 4.0.3 on 2022-03-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='lat',
            field=models.CharField(default=1, max_length=50, verbose_name='Latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='log',
            field=models.CharField(default=1, max_length=50, verbose_name='Longitude'),
            preserve_default=False,
        ),
    ]
