# Generated by Django 4.1.1 on 2022-09-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_store_lat_store_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Endereco'),
        ),
        migrations.AlterField(
            model_name='store',
            name='close',
            field=models.TimeField(blank=True, null=True, verbose_name='Fecho'),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Descricao'),
        ),
        migrations.AlterField(
            model_name='store',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='store',
            name='lat',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='store',
            name='log',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='store',
            name='open',
            field=models.TimeField(blank=True, null=True, verbose_name='Abertura'),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefone'),
        ),
    ]
